// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB75EbGCJSFGYp4UvUSGGyAXdpMT4Abrlk',
    appId: '1:208848159580:web:0b261795e11f6bb68ab799',
    messagingSenderId: '208848159580',
    projectId: 'profile-listing-caaa5',
    authDomain: 'profile-listing-caaa5.firebaseapp.com',
    storageBucket: 'profile-listing-caaa5.firebasestorage.app',
    measurementId: 'G-KZGJF9XLES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzvFXoE9AxU7DWx9SiuN2scq1Im6f2YlQ',
    appId: '1:208848159580:android:1100ccbe481ca0b08ab799',
    messagingSenderId: '208848159580',
    projectId: 'profile-listing-caaa5',
    storageBucket: 'profile-listing-caaa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3uHup7cOX7e0Uw6vX0-mw3JVFde_rTlU',
    appId: '1:208848159580:ios:1f89412cbc8c20388ab799',
    messagingSenderId: '208848159580',
    projectId: 'profile-listing-caaa5',
    storageBucket: 'profile-listing-caaa5.firebasestorage.app',
    iosBundleId: 'com.example.profileListing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3uHup7cOX7e0Uw6vX0-mw3JVFde_rTlU',
    appId: '1:208848159580:ios:1f89412cbc8c20388ab799',
    messagingSenderId: '208848159580',
    projectId: 'profile-listing-caaa5',
    storageBucket: 'profile-listing-caaa5.firebasestorage.app',
    iosBundleId: 'com.example.profileListing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB75EbGCJSFGYp4UvUSGGyAXdpMT4Abrlk',
    appId: '1:208848159580:web:6fb418c94fefd4708ab799',
    messagingSenderId: '208848159580',
    projectId: 'profile-listing-caaa5',
    authDomain: 'profile-listing-caaa5.firebaseapp.com',
    storageBucket: 'profile-listing-caaa5.firebasestorage.app',
    measurementId: 'G-MV28T5BY6N',
  );
}
